<!--<div class="page-actions">-->
<!--    <div class="page-actions-inner">-->
<!--        <div class="page-actions-buttons">-->
<!--            <button-->
<!--                class="action-primary"-->
<!--                title="--><?php //echo __('New movie') ?><!--">-->
<!--                --><?php //echo __('New movie') ?>
<!--            </button>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->